name: DeployPackageProcessTemplate

on:
  push:
    branches: 
      - main
jobs:
  octopus-deployment:
    runs-on: ubuntu-latest
    env:
      OCTOPUS_SPACE: 'Clare'
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}

    steps:
    # Action to Create a Release
    - name: Create a release in Octopus Deploy 🐙
      uses: OctopusDeploy/create-release-action@v3
      with:
        project: 'PlatformHubPackageDeploy'
        release_number: '2.0.0'
        packages: |
         Run a Process Template:JhubSite:2.0.0
