on:
  push:
    branches: 
      - master
      - test
      - main
env:
  OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_SPACE: 'Clare'
steps:
  # ...
  - name: Create a release in Octopus Deploy 🐙
    id: create_a_release_in_octopus_deploy  
    uses: OctopusDeploy/create-release-action@v4
    with:
      project: 'PlatformHubPackageDeploy'
      packages: |
        Run a Process Template:JhubSite:2020.1.1.0
