name: Test Octopus OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Octopus
        uses: OctopusDeploy/login@v2
        with:
          server: ${{ secrets.OCTOPUSCLOUDURL }}
          service_account_id: 5e39c960-9e2c-44c5-bd84-a9651dc47cfc

      - name: Test login
        run: |
          echo "Octopus login succeeded"
