name: Package and Push to Octopus

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  OCTOPUS_SERVER: https://octopus-operations.octopus.app
  OCTOPUS_SPACE: Default
  PACKAGE_ID: clm-fe
  PACKAGE_VERSION: 0.0.98
  
jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Octopus
        uses: OctopusDeploy/login@v2
        with:
          server: ${{ env.OCTOPUS_SERVER }}
          service_account_id: 5e39c960-9e2c-44c5-bd84-a9651dc47cfc

      - name: Create ZIP package
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: ${{ env.PACKAGE_ID }}
          version: ${{ env.PACKAGE_VERSION }}
          output_folder: ./output
          base_path: ./packages
          files: |
            test.txt

      - name: Push package to Octopus
        uses: OctopusDeploy/push-package-action@v3
        with:
          packages: |
            ./output/*.zip
